services:
  - type: web
    name: mark-link
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mark-link
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: mark-link
    plan: free
    postgresMajorVersion: 16